GET https://goscrum-api.alkemy.org/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvcnJlb0ByZWdpc3Rlci5jb20iLCJyb2xlIjoiVGVhbSBMZWFkZXIiLCJ1c2VyTmFtZSI6InVzZXJSZWciLCJ0ZWFtSWQiOiIzNjczOWVhNC1lYjViLTQ2ODgtYmM3ZS0xNTZiZGE3NWMwZjYiLCJ1c2VySWQiOiI2MjdkNDhiMzYxOGVjYjFmNDMxODVjMzIiLCJpYXQiOjE2NTI1NzkyNjAsImV4cCI6MTY1MjY2NTY2MH0.KC9ZMMBje4cGkalzNnH9x100bTgrso72umngozS0ro4