POST https://goscrum-api.alkemy.org/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvcnJlb0ByZWdpc3Rlci5jb20iLCJyb2xlIjoiVGVhbSBMZWFkZXIiLCJ1c2VyTmFtZSI6InVzZXJSZWciLCJ0ZWFtSWQiOiIzNjczOWVhNC1lYjViLTQ2ODgtYmM3ZS0xNTZiZGE3NWMwZjYiLCJ1c2VySWQiOiI2MjdkNDhiMzYxOGVjYjFmNDMxODVjMzIiLCJpYXQiOjE2NTI0MjEyMDcsImV4cCI6MTY1MjUwNzYwN30.p4BtN_frKopt72WUUB-PWLEsCAuFONI1Mz26wK0bCvc

{
  "task": {
    "title": "title1",
    "status": "NEW",
    "importance": "HIGH",
    "description": "Desc1"
  }
}

###

POST https://goscrum-api.alkemy.org/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvcnJlb0ByZWdpc3RlcjUuY29tIiwicm9sZSI6IlRlYW0gTWVtYmVyIiwidXNlck5hbWUiOiJ1c2VyTmV3IiwidGVhbUlkIjoiMzY3MzllYTQtZWI1Yi00Njg4LWJjN2UtMTU2YmRhNzVjMGY2IiwidXNlcklkIjoiNjI4MDY4ZTY3OGY3ZTZiNDE2YjEyODA5IiwiaWF0IjoxNjUyNTgyNjY2LCJleHAiOjE2NTI2NjkwNjZ9.tH098ZQvc9jBaaApZ8qPuoniFeNRcX0xmDIEDVgKYIM

{
  "task": {
    "title": "title5",
    "status": "FINISHED",
    "importance": "MEDIUM",
    "description": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, officia facilis id sunt eius velit officiis unde error dolorem harum provident similique tenetur! Debitis ipsam sit quia omnis libero vero qui incidunt, asperiores provident quae, recusandae, cupiditate quos ipsum. Ipsam tempore voluptatibus dolore fuga minima illum voluptatum, distinctio iure non accusantium quia at! In veritatis ipsum laudantium facilis eos expedita!"
  }
}