POST https://goscrum-api.alkemy.org/auth/login
content-type: application/json

{
  "userName": "userReg",
  "password": "123456"
}

###
POST https://goscrum-api.alkemy.org/auth/login
content-type: application/json

{
  "userName": "userNew",
  "password": "123456"
}