POST https://goscrum-api.alkemy.org/auth/register
content-type: application/json

{
  "user": {
    "userName": "userReg",
    "password": "123456",
    "email": "correo@register.com",
    "teamID": "36739ea4-eb5b-4688-bc7e-156bda75c0f6",
    "role": "Team Leader",
    "continent": "Europa",
    "region": "Otro"
  }
}

###

POST https://goscrum-api.alkemy.org/auth/register
content-type: application/json

{
  "user": {
    "userName": "userNew",
    "password": "123456",
    "email": "correo@register5.com",
    "teamID": "36739ea4-eb5b-4688-bc7e-156bda75c0f6",
    "role": "Team Member",
    "continent": "Europa",
    "region": "Otro"
  }
}